# image for webclient
FROM alpine:latest

RUN apk update && \
	apk upgrade && \
	apk add python && \
	apk add py-pip && \
	apk add bash

COPY ./webclient/entrypoint.sh /
COPY ./webclient /opt/project/webclient/
COPY ./worker /opt/project/worker/
COPY ./crawler /opt/project/crawler/
COPY ./config.json /opt/project/config.json

RUN chmod +x /entrypoint.sh

ENV PYTHONPATH /opt/project/
WORKDIR /opt/project/webclient/

RUN pip install -r requirements.txt

RUN adduser -D -g '' user

RUN rm -rf /var/cache/apk/*