# image for web
FROM honeynet/thug:latest

RUN cd /opt/thug/src && \
    python setup.py install

COPY ./webclient/entrypoint.sh /
COPY ./webclient /opt/project/web/
COPY ./thugworker /opt/project/thugworker/
COPY ./config.json /opt/project/config.json

RUN chmod +x /entrypoint.sh

ENV PYTHONPATH /opt/project/
WORKDIR /opt/project/web/

RUN pip install -r requirements.txt

RUN adduser --disabled-password --gecos '' user