# WORKER IMAGE
FROM honeynet/thug:latest

# INSTALL THUG
RUN cd /opt/thug/src && \
    python setup.py install

# CREATE FOLDER STRUCTURE
COPY ./worker/entrypoint.sh /
COPY ./worker /opt/project/worker/

# CREATE USER, ENV_PATHS
RUN chmod +x /entrypoint.sh
ENV PYTHONPATH /opt/project/
WORKDIR /opt/project/worker/
RUN adduser --disabled-password --gecos '' user

# INSTALL PYTHON DEPENDENCIES
RUN pip install -r requirements.txt

# COPY CONFIG
COPY ./config.json /opt/project/config.json

