BROKER_URL = 'redis://redis:6379'

MONGODB_URL = 'mongodb://db:27017'
MONGODB_DATABASE = 'thug'


GEOIP2_WEB_SERVICE_USER_ID = None
GEOIP2_WEB_SERVICE_LICENSE_KEY = None
GEOIP2_WEB_SERVICE_TYPE = None

GEOIP2_DATABASE_PATH = None
GEOIP2_DATABASE_TYPE = None
